# Generated by Django 3.2.20 on 2023-10-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-made_at']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='account_owner',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='edited_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='made_at',
        ),
    ]
