# Generated by Django 3.2.20 on 2023-10-10 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20231010_1703'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-made_at']},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='owner',
            new_name='account_owner',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='made_at',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('account_owner', 'post')},
        ),
    ]
